/**
 * App.tsx uses the lightweight stepper renderer for interactive preview:
 *   compiled V2.1 timeline → CHAPTERS[] → useStepper → Component → Stage
 *
 * The compiled spec is the source for narration and fallback beat duration.
 * MasterClock/CueResolver remain reserved for the locked-audio render path.
 *
 * Legacy path keeps Manual/Audio/Auto/Clean recording modes working.
 * New V2.1 features (claims.json, DESIGN.md, video-spec.yaml, compiler,
 * timeline.json) are consumed by the compiler and QA pipeline, not by
 * this legacy rendering path.
 */
import "./styles/fonts.css"; // project-local fonts or deterministic draft fallbacks
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ErrorBoundary } from "./components/ErrorBoundary";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { usePlaybackControls } from "./hooks/usePlaybackControls";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";
import timeline from "./generated/timeline.json";

const COMPILED_BEATS = timeline.chapters.flatMap((chapter) =>
  chapter.scenes.flatMap((scene) => scene.beats),
);

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";
  const compiledDurationMs =
    (COMPILED_BEATS[stepper.globalIndex]?.durationUs ?? 0) / 1000;

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();
  usePlaybackControls({ mode, cycleMode, autoStarted, setAutoStarted, stepper });
  const clean = new URLSearchParams(window.location.search).get("clean") === "1";

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: compiledDurationMs || estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage
        chapterId={ch.id}
        sceneId={ch.sceneIds?.[stepper.cursor.step] ?? ch.id}
        onAdvance={mode === "auto" ? () => undefined : stepper.next}
      >
        <ErrorBoundary
          key={ch.id}
          chapterId={ch.id}
          fatal={clean || import.meta.env.PROD}
        >
          <div className="scene">
            <Cmp step={stepper.cursor.step} />
          </div>
        </ErrorBoundary>
      </Stage>
      {!clean && (
        <>
          <ProgressBar
            chapters={CHAPTERS}
            cursor={stepper.cursor}
            onJumpChapter={stepper.jumpToChapter}
          />
          <AutoToggle mode={mode} onCycle={cycleMode} />
          <AutoStartGate
            visible={mode === "auto" && !autoStarted}
            onStart={() => setAutoStarted(true)}
          />
        </>
      )}
    </>
  );
}
